## 필요 라이브러리 임포트

In [313]:
import numpy as np
import pandas as pd
import openpyxl
import matplotlib.pyplot as plt
import seaborn as sns

## 데이터 로드

In [314]:
lotto600_df = pd.read_excel('./data/lotto600.xlsx')
lotto600_df.head()

,회차별 추첨결과,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,년도,회차,추첨일,1등,NaN,2등,NaN,3등,NaN,4등,NaN,5등,NaN,당첨번호,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,당첨자수,당첨금액,당첨자수,당첨금액,당첨자수,당첨금액,당첨자수,당첨금액,당첨자수,당첨금액,1,2.0,3.0,4.0,5.0,6.0,보너스
2,2014,600,2014.05.31,15,"901,798,725원",41,"54,987,728원",1518,"1,485,176원",77138,"50,000원",1258677,"5,000원",5,11.0,14.0,27.0,29.0,36.0,44
3,NaN,599,2014.05.24,8,"1,710,918,329원",43,"53,051,732원",1685,"1,353,843원",79069,"50,000원",1297530,"5,000원",5,12.0,17.0,29.0,34.0,35.0,27
4,NaN,598,2014.05.17,16,"833,998,594원",50,"44,479,925원",2053,"1,083,291원",86005,"50,000원",1333411,"5,000원",4,12.0,24.0,33.0,38.0,45.0,22

In [315]:
lotto1184_df = pd.read_excel('./data/lotto1184.xlsx')
lotto1184_df.head()

,회차별 추첨결과,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,년도,회차,추첨일,1등,NaN,2등,NaN,3등,NaN,4등,NaN,5등,NaN,당첨번호,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,당첨자수,당첨금액,당첨자수,당첨금액,당첨자수,당첨금액,당첨자수,당첨금액,당첨자수,당첨금액,1,2.0,3.0,4.0,5.0,6.0,보너스
2,2025,1184,2025.08.09,15,"1,910,655,600원",95,"50,280,411원",3115,"1,533,432원",155556,"50,000원",2576710,"5,000원",14,16.0,23.0,25.0,31.0,37.0,42
3,NaN,1183,2025.08.02,13,"2,073,966,000원",92,"48,843,403원",3623,"1,240,297원",169030,"50,000원",2680548,"5,000원",4,15.0,17.0,23.0,27.0,36.0,31
4,NaN,1182,2025.07.26,13,"2,124,785,424원",79,"58,274,706원",3015,"1,526,933원",156025,"50,000원",2616958,"5,000원",1,13.0,21.0,25.0,28.0,31.0,22

## 전처리

### 1회차 ~ 600회차

In [316]:
column = [
    '년도', '회차', '추첨일', '1등_당첨자수', '1등_당첨금액',
    '2등_당첨자수', '2등_당첨금액', '3등_당첨자수', '3등_당첨금액', 
    '4등_당첨자수', '4등_당첨금액', '5등_당첨자수', '5등_당첨금액', 
    '당첨번호_1', '당첨번호_2', '당첨번호_3', '당첨번호_4', '당첨번호_5', '당첨번호_6', '보너스번호'
]

lotto600_df.columns = column
lotto600_df = lotto600_df.drop(index=[0, 1], axis=1).reset_index(drop=True)
lotto600_df.head()

,년도,회차,추첨일,1등_당첨자수,1등_당첨금액,2등_당첨자수,2등_당첨금액,3등_당첨자수,3등_당첨금액,4등_당첨자수,4등_당첨금액,5등_당첨자수,5등_당첨금액,당첨번호_1,당첨번호_2,당첨번호_3,당첨번호_4,당첨번호_5,당첨번호_6,보너스번호
0,2014,600,2014.05.31,15,"901,798,725원",41,"54,987,728원",1518,"1,485,176원",77138,"50,000원",1258677,"5,000원",5,11.0,14.0,27.0,29.0,36.0,44
1,NaN,599,2014.05.24,8,"1,710,918,329원",43,"53,051,732원",1685,"1,353,843원",79069,"50,000원",1297530,"5,000원",5,12.0,17.0,29.0,34.0,35.0,27
2,NaN,598,2014.05.17,16,"833,998,594원",50,"44,479,925원",2053,"1,083,291원",86005,"50,000원",1333411,"5,000원",4,12.0,24.0,33.0,38.0,45.0,22
3,NaN,597,2014.05.10,13,"1,057,920,606원",46,"49,829,594원",1532,"1,496,189원",75553,"50,000원",1260248,"5,000원",8,10.0,23.0,24.0,35.0,43.0,37
4,NaN,596,2014.05.03,10,"1,328,267,663원",41,"53,994,621원",1651,"1,340,872원",80007,"50,000원",1313990,"5,000원",3,4.0,12.0,14.0,25.0,43.0,17

In [317]:
lotto600_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   년도       13 non-null     object
 1   회차       600 non-null    object
 2   추첨일      600 non-null    object
 3   1등_당첨자수  600 non-null    object
 4   1등_당첨금액  600 non-null    object
 5   2등_당첨자수  600 non-null    object
 6   2등_당첨금액  600 non-null    object
 7   3등_당첨자수  600 non-null    object
 8   3등_당첨금액  600 non-null    object
 9   4등_당첨자수  600 non-null    object
 10  4등_당첨금액  600 non-null    object
 11  5등_당첨자수  600 non-null    object
 12  5등_당첨금액  600 non-null    object
 13  당첨번호_1   600 non-null    object
 14  당첨번호_2   600 non-null    float64
 15  당첨번호_3   600 non-null    float64
 16  당첨번호_4   600 non-null    float64
 17  당첨번호_5   600 non-null    float64
 18  당첨번호_6   600 non-null    float64
 19  보너스번호    600 non-null    object
dtypes: float64(5), object(15)
memory usage: 93.9+ KB

In [318]:
# 결측치 처리
for i in range(600):
    lotto600_df.loc[i, '년도'] = lotto600_df.loc[i, '추첨일'][0:4]
    
# 추첨일 정수 변환
lotto600_df['추첨일'] = lotto600_df['추첨일'].str.replace('.', '')

# , and 원 제거
for i in range(1, 6):
    lotto600_df[f'{ i }등_당첨금액'] = (
        lotto600_df[f'{ i }등_당첨금액']
        .str.replace(',', '')
        .str.replace('원', '')
    )
    
lotto600_df = lotto600_df.astype(int)

lotto600_df.info()
lotto600_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   년도       600 non-null    int64
 1   회차       600 non-null    int64
 2   추첨일      600 non-null    int64
 3   1등_당첨자수  600 non-null    int64
 4   1등_당첨금액  600 non-null    int64
 5   2등_당첨자수  600 non-null    int64
 6   2등_당첨금액  600 non-null    int64
 7   3등_당첨자수  600 non-null    int64
 8   3등_당첨금액  600 non-null    int64
 9   4등_당첨자수  600 non-null    int64
 10  4등_당첨금액  600 non-null    int64
 11  5등_당첨자수  600 non-null    int64
 12  5등_당첨금액  600 non-null    int64
 13  당첨번호_1   600 non-null    int64
 14  당첨번호_2   600 non-null    int64
 15  당첨번호_3   600 non-null    int64
 16  당첨번호_4   600 non-null    int64
 17  당첨번호_5   600 non-null    int64
 18  당첨번호_6   600 non-null    int64
 19  보너스번호    600 non-null    int64
dtypes: int64(20)
memory usage: 93.9 KB

,년도,회차,추첨일,1등_당첨자수,1등_당첨금액,2등_당첨자수,2등_당첨금액,3등_당첨자수,3등_당첨금액,4등_당첨자수,4등_당첨금액,5등_당첨자수,5등_당첨금액,당첨번호_1,당첨번호_2,당첨번호_3,당첨번호_4,당첨번호_5,당첨번호_6,보너스번호
0,2014,600,20140531,15,901798725,41,54987728,1518,1485176,77138,50000,1258677,5000,5,11,14,27,29,36,44
1,2014,599,20140524,8,1710918329,43,53051732,1685,1353843,79069,50000,1297530,5000,5,12,17,29,34,35,27
2,2014,598,20140517,16,833998594,50,44479925,2053,1083291,86005,50000,1333411,5000,4,12,24,33,38,45,22
3,2014,597,20140510,13,1057920606,46,49829594,1532,1496189,75553,50000,1260248,5000,8,10,23,24,35,43,37
4,2014,596,20140503,10,1328267663,41,53994621,1651,1340872,80007,50000,1313990,5000,3,4,12,14,25,43,17

### 601회차 ~ 1184회차

In [319]:
column = [
    '년도', '회차', '추첨일', '1등_당첨자수', '1등_당첨금액',
    '2등_당첨자수', '2등_당첨금액', '3등_당첨자수', '3등_당첨금액', 
    '4등_당첨자수', '4등_당첨금액', '5등_당첨자수', '5등_당첨금액', 
    '당첨번호_1', '당첨번호_2', '당첨번호_3', '당첨번호_4', '당첨번호_5', '당첨번호_6', '보너스번호'
]

lotto1184_df.columns = column
lotto1184_df = lotto1184_df.drop(index=[0, 1], axis=1).reset_index(drop=True)
lotto1184_df.head()

,년도,회차,추첨일,1등_당첨자수,1등_당첨금액,2등_당첨자수,2등_당첨금액,3등_당첨자수,3등_당첨금액,4등_당첨자수,4등_당첨금액,5등_당첨자수,5등_당첨금액,당첨번호_1,당첨번호_2,당첨번호_3,당첨번호_4,당첨번호_5,당첨번호_6,보너스번호
0,2025,1184,2025.08.09,15,"1,910,655,600원",95,"50,280,411원",3115,"1,533,432원",155556,"50,000원",2576710,"5,000원",14,16.0,23.0,25.0,31.0,37.0,42
1,NaN,1183,2025.08.02,13,"2,073,966,000원",92,"48,843,403원",3623,"1,240,297원",169030,"50,000원",2680548,"5,000원",4,15.0,17.0,23.0,27.0,36.0,31
2,NaN,1182,2025.07.26,13,"2,124,785,424원",79,"58,274,706원",3015,"1,526,933원",156025,"50,000원",2616958,"5,000원",1,13.0,21.0,25.0,28.0,31.0,22
3,NaN,1181,2025.07.19,17,"1,593,643,500원",86,"52,503,759원",3109,"1,452,340원",155938,"50,000원",2596371,"5,000원",8,10.0,14.0,20.0,33.0,41.0,28
4,NaN,1180,2025.07.12,11,"2,535,566,421원",72,"64,563,034원",3010,"1,544,365원",153274,"50,000원",2567395,"5,000원",6,12.0,18.0,37.0,40.0,41.0,3

In [320]:
lotto1184_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   년도       12 non-null     object
 1   회차       584 non-null    object
 2   추첨일      584 non-null    object
 3   1등_당첨자수  584 non-null    object
 4   1등_당첨금액  584 non-null    object
 5   2등_당첨자수  584 non-null    object
 6   2등_당첨금액  584 non-null    object
 7   3등_당첨자수  584 non-null    object
 8   3등_당첨금액  584 non-null    object
 9   4등_당첨자수  584 non-null    object
 10  4등_당첨금액  584 non-null    object
 11  5등_당첨자수  584 non-null    object
 12  5등_당첨금액  584 non-null    object
 13  당첨번호_1   584 non-null    object
 14  당첨번호_2   584 non-null    float64
 15  당첨번호_3   584 non-null    float64
 16  당첨번호_4   584 non-null    float64
 17  당첨번호_5   584 non-null    float64
 18  당첨번호_6   584 non-null    float64
 19  보너스번호    584 non-null    object
dtypes: float64(5), object(15)
memory usage: 91.4+ KB

In [321]:
# 결측치 처리
for i in range(584):
    lotto1184_df.loc[i, '년도'] = lotto1184_df.loc[i, '추첨일'][0:4]
    
# 추첨일 정수 변환
lotto1184_df['추첨일'] = lotto1184_df['추첨일'].str.replace('.', '')

# , and 원 제거
for i in range(1, 6):
    lotto1184_df[f'{ i }등_당첨금액'] = (
        lotto1184_df[f'{ i }등_당첨금액']
        .str.replace(',', '')
        .str.replace('원', '')
    )
    
lotto1184_df = lotto1184_df.astype(int)

lotto1184_df.info()
lotto1184_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   년도       584 non-null    int64
 1   회차       584 non-null    int64
 2   추첨일      584 non-null    int64
 3   1등_당첨자수  584 non-null    int64
 4   1등_당첨금액  584 non-null    int64
 5   2등_당첨자수  584 non-null    int64
 6   2등_당첨금액  584 non-null    int64
 7   3등_당첨자수  584 non-null    int64
 8   3등_당첨금액  584 non-null    int64
 9   4등_당첨자수  584 non-null    int64
 10  4등_당첨금액  584 non-null    int64
 11  5등_당첨자수  584 non-null    int64
 12  5등_당첨금액  584 non-null    int64
 13  당첨번호_1   584 non-null    int64
 14  당첨번호_2   584 non-null    int64
 15  당첨번호_3   584 non-null    int64
 16  당첨번호_4   584 non-null    int64
 17  당첨번호_5   584 non-null    int64
 18  당첨번호_6   584 non-null    int64
 19  보너스번호    584 non-null    int64
dtypes: int64(20)
memory usage: 91.4 KB

,년도,회차,추첨일,1등_당첨자수,1등_당첨금액,2등_당첨자수,2등_당첨금액,3등_당첨자수,3등_당첨금액,4등_당첨자수,4등_당첨금액,5등_당첨자수,5등_당첨금액,당첨번호_1,당첨번호_2,당첨번호_3,당첨번호_4,당첨번호_5,당첨번호_6,보너스번호
0,2025,1184,20250809,15,1910655600,95,50280411,3115,1533432,155556,50000,2576710,5000,14,16,23,25,31,37,42
1,2025,1183,20250802,13,2073966000,92,48843403,3623,1240297,169030,50000,2680548,5000,4,15,17,23,27,36,31
2,2025,1182,20250726,13,2124785424,79,58274706,3015,1526933,156025,50000,2616958,5000,1,13,21,25,28,31,22
3,2025,1181,20250719,17,1593643500,86,52503759,3109,1452340,155938,50000,2596371,5000,8,10,14,20,33,41,28
4,2025,1180,20250712,11,2535566421,72,64563034,3010,1544365,153274,50000,2567395,5000,6,12,18,37,40,41,3

## 병합

In [322]:
lotto_df = pd.concat([lotto1184_df, lotto600_df], ignore_index=True)
lotto_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1184 entries, 0 to 1183
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   년도       1184 non-null   int64
 1   회차       1184 non-null   int64
 2   추첨일      1184 non-null   int64
 3   1등_당첨자수  1184 non-null   int64
 4   1등_당첨금액  1184 non-null   int64
 5   2등_당첨자수  1184 non-null   int64
 6   2등_당첨금액  1184 non-null   int64
 7   3등_당첨자수  1184 non-null   int64
 8   3등_당첨금액  1184 non-null   int64
 9   4등_당첨자수  1184 non-null   int64
 10  4등_당첨금액  1184 non-null   int64
 11  5등_당첨자수  1184 non-null   int64
 12  5등_당첨금액  1184 non-null   int64
 13  당첨번호_1   1184 non-null   int64
 14  당첨번호_2   1184 non-null   int64
 15  당첨번호_3   1184 non-null   int64
 16  당첨번호_4   1184 non-null   int64
 17  당첨번호_5   1184 non-null   int64
 18  당첨번호_6   1184 non-null   int64
 19  보너스번호    1184 non-null   int64
dtypes: int64(20)
memory usage: 185.1 KB

In [323]:
lotto_df.head()

,년도,회차,추첨일,1등_당첨자수,1등_당첨금액,2등_당첨자수,2등_당첨금액,3등_당첨자수,3등_당첨금액,4등_당첨자수,4등_당첨금액,5등_당첨자수,5등_당첨금액,당첨번호_1,당첨번호_2,당첨번호_3,당첨번호_4,당첨번호_5,당첨번호_6,보너스번호
0,2025,1184,20250809,15,1910655600,95,50280411,3115,1533432,155556,50000,2576710,5000,14,16,23,25,31,37,42
1,2025,1183,20250802,13,2073966000,92,48843403,3623,1240297,169030,50000,2680548,5000,4,15,17,23,27,36,31
2,2025,1182,20250726,13,2124785424,79,58274706,3015,1526933,156025,50000,2616958,5000,1,13,21,25,28,31,22
3,2025,1181,20250719,17,1593643500,86,52503759,3109,1452340,155938,50000,2596371,5000,8,10,14,20,33,41,28
4,2025,1180,20250712,11,2535566421,72,64563034,3010,1544365,153274,50000,2567395,5000,6,12,18,37,40,41,3

In [324]:
lotto_df.tail()

,년도,회차,추첨일,1등_당첨자수,1등_당첨금액,2등_당첨자수,2등_당첨금액,3등_당첨자수,3등_당첨금액,4등_당첨자수,4등_당첨금액,5등_당첨자수,5등_당첨금액,당첨번호_1,당첨번호_2,당첨번호_3,당첨번호_4,당첨번호_5,당첨번호_6,보너스번호
1179,2003,5,20030104,0,0,0,0,42,6033800,3043,166500,60434,10000,16,24,29,40,41,42,3
1180,2002,4,20021228,0,0,1,211191200,29,7282400,2777,152100,52382,10000,14,27,30,31,40,42,2
1181,2002,3,20021221,1,2000000000,0,0,139,1174100,5940,54900,73256,10000,11,16,19,21,27,31,30
1182,2002,2,20021214,1,2002006800,2,94866800,103,1842000,3763,100800,55480,10000,9,13,21,25,32,42,2
1183,2002,1,20021207,0,0,1,143934100,28,5140500,2537,113400,40155,10000,10,23,29,33,37,40,16

### 파일 저장

In [325]:
lotto_df.to_excel('./data/lotto_df.xlsx')